sudo: required
services: 
     - docker:
before install:
    - docker build -t shalu/react-app -f Dockerfile.dev .

scripts: 
    - docker run -e CI=true shalu/react-app npm run test         

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-633821185950"
  bucket_path: "Docker-react"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 